services:
  - type: web
    name: mindbloom
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
      - key: DATABASE_URL
        value: file:/var/data/dev.db
      - key: PORT
        value: 10000
      # Set the following in Render UI or via secrets
      - key: JWT_SECRET
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
    disks:
      - name: data
        mountPath: /var/data
        sizeGiB: 1
